FROM rust:1.82

WORKDIR /app
COPY . .

# 安装依赖
RUN apt-get update && apt-get install -y protobuf-compiler

# 编译项目
RUN cargo build --release

# 设置环境变量
ENV PORT=3111

# 暴露端口
EXPOSE 3111

# 启动命令
CMD ["./target/release/cursor-api"]